---
title: "plotting_exercises"
format: html
---

### Monday 6/23 Penguin Data Plotting Exercises

```{r}
#library("tidyverse")
#library("ggplot2")
#library("dataRetrieval")
#library("readr")
#library("cowplot")
#library("googleway")
#library("ggrepel")
#library("ggspatial")
#library("sf")
#library("rnaturalearth")
#library("rnaturalearthdata")
#library("prismatic")
```

```{r}
ggplot(data = penguins,
       mapping = aes(x= flipper_len, y = body_mass)
       )+
  geom_point(aes(color = species, shape = species))+
  geom_smooth(method = "lm")+
  labs(
    title = "Body Mass and Flipper Length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper Length (mm)", y = "Body Mass (g)",
    color = "Species", shape = "Species"
  )
```

```{r}
penguins|>
  ggplot(aes(x = body_mass))+
  geom_histogram(binwidth = 200)+
  labs(
    title = "Penguin Size Distribution",
    subtitle = "Adelie, Chinstrap, and Gentoo penguins",
    x = "Body Mass (g)", y = "Count")
```

```{r}
penguins|>
  ggplot(aes(x = species, y = body_mass))+
  geom_boxplot(
    aes(color = species,
        fill = after_scale(clr_desaturate(clr_lighten(color,.6),.6))),
    linewidth = 1
  )+
  labs(
    title = "Body Mass by Species",
    subtitle = "Statistics for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Species", y = "Body Mass (g)"
  )+
  scale_color_brewer(palette = "Dark2", guide = "none")+
  theme_set(theme_bw())+
  theme(axis.title.x = element_text(margin = margin(t=10), size = 13),
        axis.title.y = element_text(margin = margin(r=10), size = 13))
```
