---
title: "Sucralose_Dataset"
format: html
---

```{r}
library("tidyverse")
library("ggplot2")
library("dataRetrieval")
library("readr")
library("cowplot")
library("googleway")
library("ggrepel")
library("ggspatial")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("prismatic")
```

```{r}
(sucralose_raw <- readr::read_csv("sucralose_simplified.csv", col_types = cols(
  Date = col_date("%m.%d.%Y"),
)))
```

```{r}
sucralose <- sucralose_raw|>
  mutate(add_column(sucralose_raw,
    gage_name = case_when(
      str_detect(sys_sample_code, "CM") ~ "Comal Springs",
      str_detect(sys_sample_code, "SM") ~ "San Marcos Springs")))|>
  relocate("gage_name",.before="Date")

sucralose_no_dup <- subset(sucralose,duplicate == "N")
sucralose_no_dup_blank <- subset(sucralose, blank == "N")
```

```{r}
theme_set(theme_bw())
sucralose_plot <- sucralose|>
  group_by(gage_name,month)|>
  summarize(sucralose_mean = mean(result_value, na.rm=TRUE))|>
  ungroup()|>
  ggplot(aes(month, sucralose_mean, color=gage_name))+
  geom_point()+
  scale_x_continuous(breaks=c(1,2,3,4,5,6,7,8,9,10,11,12))+
  labs(
    title = "Sucralose by Gage and Month",
    subtitle = "Comal and San Marcos Rivers",
    x = "Month", y = "Average Sucralose (ng/L)")+
  theme(axis.title.x = element_text(margin = margin(t=5)),
        axis.title.y = element_text(margin = margin(r=10)))+
  scale_color_discrete(
    name = "Gage",
    labels = c("Comal River Spring Run 3", "San Marcos Springs Hotel Site"))
sucralose_plot
```

### Analyzing quality of sucralose data

```{r}
suc_detected <- sucralose|>
  filter(detect_flag == "Y")

false_pos <- suc_detected|>
  filter(blank == "Y")
```

```{r}
duplicates <- sucralose|>
  filter(gage_name %in% c("San Marcos Springs","Comal Springs"),
         duplicate == "Y" | lead(duplicate) == "Y")|>
  mutate(label = case_when(
    str_detect(duplicate, "N")~"Original",
    str_detect(duplicate, "Y")~"Duplicate"
  ))

dup_plot <- duplicates|>
  ggplot()+
  geom_point(aes(x = Date, y = result_value, color = label))
dup_plot
```
